### PR TITLE
Alis tjplat 1010 remove internatinoal references

### PR DESCRIPTION
**Pull request by alis-stripe**
Remove International references from Docs

### CODE REVIEW

**Comment by saville-stripe** [comment]
image
Seeing a couple of things... I think blog doesn't matter, but what about magento?

**Comment by alis-stripe** [comment]
Line 19 for both magento articles should be removed. I'll do that now.

The other bits are intentionally left.
- Magento references to custom or international rates, those are rates the merchant would add to their rates table in Magento and are not populated by TaxJar.
- Changelog
- I didn't audit the blog

**Comment by alis-stripe** [comment]
@saville-stripe this is ready for re-review, thanks!

**Review by saville-stripe — APPROVED** [review]
LGTM

**Pull request merged**
